default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres_db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: geolocation_development


test:
  <<: *default
  database: geolocation_test